"""baseline

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-26 21:28:18.863668
"""
from alembic import op
import sqlalchemy as sa


revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memories',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'key')
    )
    op.create_table('allowed_models',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('credential_id', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', 'model', 'credential_id', name='uq_workspace_model_credential')
    )
    with op.batch_alter_table('allowed_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowed_models_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('approval_rate_limits',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('window', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('auth_accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth_bootstrap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_invites',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('auth_login_budgets',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('blocked_until', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('revision', sa.String(length=32), nullable=False),
    sa.Column('principal', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('auth_login_budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_login_budgets_expires_at'), ['expires_at'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_account_id'), ['account_id'], unique=False)

    op.create_table('credentials',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('encrypted', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('execution_jobs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('lease_until', sa.Float(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('execution_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_jobs_status'), ['status'], unique=False)

    op.create_table('run_action_results',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('invocation', sa.String(length=300), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('run_id', 'invocation')
    )
    op.create_table('run_approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('checkpoint_owner', sa.String(length=128), nullable=False),
    sa.Column('invocation', sa.String(length=300), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('execution', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('owns_marker', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'invocation', name='uq_run_approval_invocation')
    )
    with op.batch_alter_table('run_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_approvals_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_approvals_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_approvals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_approvals_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('run_events',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('run_id', 'seq')
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('run_guard_decisions',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('run_id', 'seq')
    )
    with op.batch_alter_table('run_guard_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_guard_decisions_decision'), ['decision'], unique=False)

    op.create_table('run_token_usage',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('run_id', 'seq', 'provider', 'model')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('citation_counter', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_runs_tenant_created_id', ['tenant_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('schema_migrations',
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('tool_connections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('encrypted', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_connections_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('worker_heartbeats',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('last_seen', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_heartbeats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_heartbeats_last_seen'), ['last_seen'], unique=False)

    op.create_table('workflows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_tenant_id'))

    op.drop_table('workflows')
    with op.batch_alter_table('worker_heartbeats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_heartbeats_last_seen'))

    op.drop_table('worker_heartbeats')
    with op.batch_alter_table('tool_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_connections_tenant_id'))

    op.drop_table('tool_connections')
    op.drop_table('schema_migrations')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_tenant_id'))
        batch_op.drop_index('ix_runs_tenant_created_id')
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_created_at'))

    op.drop_table('runs')
    op.drop_table('run_token_usage')
    with op.batch_alter_table('run_guard_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_guard_decisions_decision'))

    op.drop_table('run_guard_decisions')
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_events_tenant_id'))

    op.drop_table('run_events')
    with op.batch_alter_table('run_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_approvals_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_run_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_run_approvals_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_approvals_expires_at'))

    op.drop_table('run_approvals')
    op.drop_table('run_action_results')
    with op.batch_alter_table('execution_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_jobs_status'))

    op.drop_table('execution_jobs')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_tenant_id'))

    op.drop_table('credentials')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_account_id'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('auth_login_budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_login_budgets_expires_at'))

    op.drop_table('auth_login_budgets')
    op.drop_table('auth_invites')
    op.drop_table('auth_bootstrap')
    op.drop_table('auth_accounts')
    op.drop_table('approval_rate_limits')
    with op.batch_alter_table('allowed_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowed_models_tenant_id'))

    op.drop_table('allowed_models')
    op.drop_table('agent_memories')
    # ### end Alembic commands ###
